sudo: false
language: node_js
node_js:
  - '4.0'
  - '0.12'
  - '0.10'

# Here for libSass errors. Remove when we have rubySass or libSass working well.
# https://github.com/google/web-starter-kit/pull/647
matrix:
  allow_failures:
    - node_js: iojs
